language: go
sudo: required
dist: xenial

go:
  - 1.11.1

#stages:
#  - name: build
#  - name: e2e
#  - name: deploy

env:
  matrix:
    - TEST_STUPID=smoke
    - TEST_STUPID=es
    - TEST_STUPID=cassandra

#script: "./.travis/matrix-test.sh $TEST_GROUP"

#    - stage: deploy
#      script: "echo 'This is the deploy stage'"

stages:
  - e2e

jobs:
  include:
    - stage: build
    - stage: e2e
      name: "e2e"
      env:
        matrix:
          - TEST_GROUP=fred
          - TEST_GROUP=barney
      script: "./.travis/matrix-test.sh $TEST_GROUP"