language: go
sudo: required
dist: xenial

go:
  - 1.11.1

#stages:
#  - name: build
#  - name: e2e
#  - name: deploy

env:
  matrix:
    - TEST_GROUP=smoke
    - TEST_GROUP=es
    - TEST_GROUP=cassandra

#script: "./.travis/matrix-test.sh $TEST_GROUP"

#    - stage: deploy
#      script: "echo 'This is the deploy stage'"

stages:
  - e2e

jobs:
  include:
    - stage: e2e
      name: "e2e"
      script: "./.travis/matrix-test.sh $TEST_GROUP"