# language: go
sudo: required
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial

#go:
#  - 1.11.1

stages:
  - name: build
  - name: e2e
  - name: deploy

jobs:
  include:
    - stage: build
      name: "Build"
      script:
        - "echo 'This is the build stage'"
        - "ls -alF"
        - "ls -alF ./.travis"

    - stage: e2e
      env:
        global:
          - CHANGE_MINIKUBE_NONE_USER=true
          - MINIKUBE_WANTUPDATENOTIFICATION=false
          - MINIKUBE_WANTREPORTERRORPROMPT=false
          - MINIKUBE_HOME=$HOME
          - CHANGE_MINIKUBE_NONE_USER=true
          - KUBECONFIG=$HOME/.kube/config
      install:
        - "chmod +x ./.travis/installOperator.sh"
        - "chmod +x ./.travis/rune2eTests.sh"
        - "chmod +x ./.travis/setupMinikube.sh"
        - "./.travis/setupMinikube.sh"
      script:
        - "./.travis/rune2eTests.sh"

    - stage: deploy
      script: "echo 'This is the deploy stage'"
