# language: go
sudo: required
dist: xenial

#go:
#  - 1.11.1

stages:
  - name: build
  - name: e2e
  - name: deploy

jobs:
  include:
    - stage: build
      name: "Build"
      script:
        - "echo 'This is the build stage'"

    - stage: e2e
      #install:
      #  - "./.travis/create-minikube.sh"
      #script: "./.travis/run-node-example.sh"
      script: "./.travis/matrix-test.sh"
      env:
        global:
          - CHANGE_MINIKUBE_NONE_USER=true
          - MINIKUBE_WANTUPDATENOTIFICATION=false
          - MINIKUBE_WANTREPORTERRORPROMPT=false
          - MINIKUBE_HOME=$HOME
          - CHANGE_MINIKUBE_NONE_USER=true
          - KUBECONFIG=$HOME/.kube/config
        matrix:
          - TEST_GROUP=smoke
          - TEST_GROUP=es
          - TEST_GROUP=cassandra


    - stage: deploy
      script: "echo 'This is the deploy stage'"
