#sudo: required
#dist: xenial
language: go

go:
  - "1.11.x"
  -
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    -
services:
  - docker

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  -
jobs:
  include:
  - stage: Sanity
  - script: ./create-minikube.sh
