language: go
sudo: required
dist: xenial

go:
  - 1.11.1

stages:
  - name: build
  - name: e2e
  - name: deploy

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

jobs:
  include:
    - stage: build
      name: "Build"
      script: "echo 'This is the build stage'"

    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=es
    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=smoke
    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=cassandra

    - stage: deploy
      script: "echo 'This is the deploy stage'"

notifications:
  email:
    on_failure: never
    on_success: never