language: go
sudo: required
dist: xenial

go:
  - 1.11.1

stages:
  - name: build
  - name: e2e
  - name: deploy

jobs:
  include:
    - stage: build
      name: "Build"
      script: "echo 'This is the build stage'"

    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=es
    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=smoke
    - stage: e2e
      script: "./.travis/matrix-test.sh"
      env: TEST_GROUP=cassandra

    - stage: deploy
      script: "echo 'This is the deploy stage'"
