#sudo: required
#dist: xenial
language: go

go:
  - "1.11.x"
  -
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    -
services:
  - docker

before_install:
  - chmod +x ./create-minikube.sh
  - ./create-minikube.sh
